
#' Execute Bayesian Model Using BGLR
#'
#' Executes a Bayesian model for genomic prediction using the BGLR package, incorporating specified effects and parameters. Supports optional weighting of observations.
#'
#' @param pheno_data Data frame containing the phenotypic data, where rows represent observations and columns represent variables.
#' @param response Character string specifying the column in `pheno_data` that contains the response variable.
#' @param weights An optional numeric vector of weights for the observations in the model.
#' @param ETA A list specifying the effects to be included in the model. This can include fixed effects, random effects, and any other model components as specified in BGLR documentation.
#' @param bayes_para A list containing Bayesian parameters for the model execution, including the number of iterations (`nIter`), burn-in period (`burnIn`), and thinning interval (`thin`).
#' @param verbose Logical indicating whether to print detailed output during model fitting.
#' @param core Optional; specifies the number of cores to use for parallel execution (not used in the current implementation but reserved for future use).
#' @param ... Additional arguments passed to the BGLR function.
#'
#' @return A list with two elements: `model`, which contains the model object returned by BGLR, and `output_files_names`, a vector of filenames generated by BGLR if `saveAt` is used.
#'
#' @details
#' The function simplifies the process of fitting Bayesian models in genomic prediction studies by encapsulating the BGLR model fitting process. It allows for flexible specification of model components and parameters, making it suitable for a wide range of genomic prediction scenarios. The function also handles the generation and management of output files created during model execution.
#'
#' @examples
#' # Assuming pheno_data is your phenotypic dataset with a response variable named 'Yield'
#' # and ETA lists your model components:
#' bayes_results <- bayes_mod_execute(
#'   pheno_data = pheno_data,
#'   response = "Yield",
#'   ETA = list(Fixed = ETA_Fixed, Random = ETA_Random),
#'   bayes_para = list(nIter = 10000, burnIn = 2000, thin = 10),
#'   verbose = TRUE
#' )
#' @export

bayes_mod_execute <- function(pheno_data = NULL,
                              response = NULL,
                              weights = NULL,
                              ETA = NULL,
                              bayes_para = NULL,
                              verbose = FALSE,
                              core = NULL,
                              ...){


  systime <- format(Sys.time(), "%Y%m%d_%H%M%S")
  systime <- gsub("[-: ]", "_", systime)


        fm <- BGLR::BGLR(
          y=pheno_data[, response],
          ETA=ETA,
          weights = weights,
          nIter = bayes_para[["nIter"]],
          burnIn =  bayes_para[["burnIn"]],
          thin =  bayes_para[["thin"]],
          verbose = FALSE,
          saveAt = systime)






    ## Get the name of all files stored by BGLR using the current name and time the analysis was performed
    output_files_names = list.files(pattern=systime)

    output = list(model = fm, output_files_names = output_files_names )
    #rm(output_files_names)

    names(output) <- c("model", "output_files_names")


  #}
  # ### remove the generated output files from the working directory
  # unlink(output_files_names)

  return(output)

}




