
#' Execute Bayesian Model Using BGLR
#'
#' Executes a Bayesian model for genomic prediction using the BGLR package, incorporating specified effects and parameters. Supports optional weighting of observations.
#'
#' @param pheno_data Data frame containing the phenotypic data, where rows represent observations and columns represent variables.
#' @param response Character string specifying the column in `pheno_data` that contains the response variable.
#' @param weights Optional positive Stage 2 observation precisions, supplied as
#'   a numeric vector, one-column table, or column name in `pheno_data`. For
#'   Gaussian fits these are converted to `sqrt(weights)` before calling BGLR,
#'   because BGLR defines residual variance as inverse squared native weight.
#' @param ETA A list specifying the effects to be included in the model. This can include fixed effects, random effects, and any other model components as specified in BGLR documentation.
#' @param bayes_para A list containing Bayesian parameters for the model execution, including the number of iterations (`nIter`), burn-in period (`burnIn`), and thinning interval (`thin`).
#' @param verbose Logical indicating whether to print detailed output during model fitting.
#' @param core Optional; specifies the number of cores to use for parallel execution (not used in the current implementation but reserved for future use).
#' @param GS_model Character string identifying the Bayesian model route.
#' @param response_family Response family for the Bayesian fit.
#' @param groups Optional residual-variance grouping factor for Gaussian BGLR fits.
#' @param ... Additional arguments passed to the BGLR function.
#'
#' @return A list with two elements: `model`, which contains the model object returned by BGLR, and `output_files_names`, a vector of filenames generated by BGLR if `saveAt` is used.
#'
#' @details
#' The function simplifies the process of fitting Bayesian models in genomic prediction studies by encapsulating the BGLR model fitting process. It allows for flexible specification of model components and parameters, making it suitable for a wide range of genomic prediction scenarios. The function also handles the generation and management of output files created during model execution.
#'
#' @examples
#' \dontrun{
#' # Assuming pheno_data is your phenotypic dataset with a response variable named 'Yield'
#' # and ETA lists your model components:
#' bayes_results <- bayes_mod_execute(
#'   pheno_data = pheno_data,
#'   response = "Yield",
#'   ETA = list(Fixed = ETA_Fixed, Random = ETA_Random),
#'   bayes_para = list(nIter = 10000, burnIn = 2000, thin = 10),
#'   verbose = TRUE
#' )
#' }
#' @export

bayes_mod_execute <- function(pheno_data = NULL,
                              response = NULL,
                              weights = NULL,
                              ETA = NULL,
                              bayes_para = NULL,
                              verbose = FALSE,
                              core = NULL,
                              GS_model = NULL,
                              response_family = "gaussian",
                              groups = NULL,
                              ...){

  save_prefix <- gp_bglr_save_prefix(
    model_name = GS_model %||% "BGLR",
    response = response %||% "trait"
  )

        fam <- gp_resolve_response_family(response_family, y = pheno_data[[response]])
        precision_weights <- gp_resolve_stage2_precision_weights(
          weights = weights,
          pheno_data = pheno_data,
          response = response,
          context = "BGLR Stage 2 observation weights"
        )
        if (!identical(fam, "gaussian") && isTRUE(precision_weights$supplied) &&
            any(precision_weights$precision != 1)) {
          stop(
            "BGLR ordinal/binary response fits do not support observation weights other than 1.",
            call. = FALSE
          )
        }
        bglr_weights <- if (identical(fam, "gaussian") && isTRUE(precision_weights$supplied)) {
          sqrt(precision_weights$precision)
        } else {
          NULL
        }
        if (!identical(fam, "gaussian") && !is.null(groups)) {
          stop("BGLR residual groups are supported for gaussian Bayesian fits only.", call. = FALSE)
        }
        fm <- gp_bayes_bglr_fit(
          fam = fam,
          y = gp_bayes_prepare_response(pheno_data[[response]], fam),
          response_type = gp_bayes_response_type(fam),
          ETA=ETA,
          weights = bglr_weights,
          groups = groups,
          nIter = bayes_para[["nIter"]],
          burnIn =  bayes_para[["burnIn"]],
          thin =  bayes_para[["thin"]],
          verbose = isTRUE(verbose),
          saveAt = save_prefix)






    ## Get the name of all files stored by BGLR using the current name and time the analysis was performed
    output_files_names <- list.files(
      path = dirname(save_prefix),
      pattern = paste0("^", basename(save_prefix)),
      full.names = TRUE
    )

    output = list(model = fm, output_files_names = output_files_names )
    #rm(output_files_names)

    names(output) <- c("model", "output_files_names")


  #}
  # ### remove the generated output files from the working directory
  # unlink(output_files_names)

  return(output)

}




