# Runtime prediction dispatcher used by the canonical cross-validation engine.
# This was historically embedded in the legacy runtime and is restored here
# so the new orchestration layer can call model-specific CV predictors.

#' Dispatch cross-validation prediction to a model backend
#'
#' @param model Model name to dispatch.
#' @param y Response vector.
#' @param omics_data Predictor matrix or merged omic feature matrix.
#' @param tst Test row indices.
#' @param additional_params List of model-specific parameters.
#'
#' @return Model-specific cross-validation prediction output.
#' @export
predict_with_model <- function(model = NULL,
                               y = NULL,
                               omics_data = NULL,
                               tst = NULL,
                               additional_params = NULL) {
  switch(
    model,
    "Xgboost" = AI_xgboost_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      response_family = additional_params$response_family,
      eta = additional_params$eta,
      nrounds = additional_params$nrounds,
      max_depth = additional_params$max_depth,
      scaling = additional_params$scaling,
      omic_count = additional_params$omic_count,
      centering = additional_params$centering,
      xgb_gamma = additional_params$xgb_gamma,
      colsample_bytree = additional_params$colsample_bytree,
      subsample = additional_params$subsample,
      min_child_weight = additional_params$min_child_weight,
      xgb_alpha = additional_params$xgb_alpha,
      xgb_lambda = additional_params$xgb_lambda,
      xgb_booster = additional_params$xgb_booster,
      xgb_rate_drop = additional_params$xgb_rate_drop,
      xgb_skip_drop = additional_params$xgb_skip_drop,
      xgb_objective = additional_params$xgb_objective,
      xgb_sample_type = additional_params$xgb_sample_type,
      xgb_normalize_type = additional_params$xgb_normalize_type,
      early_stop_for_iteration_xgb = additional_params$early_stop_for_iteration_xgb,
      xgb_nthread = additional_params$xgb_nthread,
      random_state = additional_params$random_state
    ),
    "cnn" = ,
    "resnet" = ,
    "ft_transformer" = ,
    "saint" = ,
    "tabnet" = ,
    "node" = ,
    "deepfm" = ,
    "dcnv2" = ,
    "nam" = ,
    "moe" = ,
    "gp_dkl" = ,
    "mlp_with_attention" = ,
    "mlp" = deep_learning_model(
      y = y,
      omics_data = omics_data,
      tst = tst,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      response_family = additional_params$response_family,
      crossval = additional_params$crossval,
      omic_count = additional_params$omic_count,
      early_stop = additional_params$early_stop,
      deep_learning_model = additional_params$deep_learning_model,
      optimizer_name = additional_params$optimizer_name,
      use_amp = additional_params$use_amp,
      max_grad_norm = additional_params$max_grad_norm,
      auto_class_weights = additional_params$auto_class_weights,
      cnn_neurons_per_layer = additional_params$cnn_neurons_per_layer,
      cnn_kernel_size = additional_params$cnn_kernel_size,
      cnn_dense_layers = additional_params$cnn_dense_layers,
      cnn_use_max_pool = additional_params$cnn_use_max_pool,
      cnn_pool_kernel = additional_params$cnn_pool_kernel,
      cnn_pool_stride = additional_params$cnn_pool_stride,
      cnn_pool_padding = additional_params$cnn_pool_padding,
      cnn_learning_rate = additional_params$cnn_learning_rate,
      cnn_separable = additional_params$cnn_separable,
      cnn_dilations = additional_params$cnn_dilations,
      cnn_use_se = additional_params$cnn_use_se,
      cnn_norm_type = additional_params$cnn_norm_type,
      cnn_pool_type = additional_params$cnn_pool_type,
      cnn_use_global_pool = additional_params$cnn_use_global_pool,
      resnet_neurons_per_block = additional_params$resnet_neurons_per_block,
      resnet_blocks = additional_params$resnet_blocks,
      resnet_learning_rate = additional_params$resnet_learning_rate,
      ft_d_model = additional_params$ft_d_model,
      ft_heads = additional_params$ft_heads,
      ft_layers = additional_params$ft_layers,
      ft_ff_mult = additional_params$ft_ff_mult,
      ft_dropout = additional_params$ft_dropout,
      ft_token_dropout = additional_params$ft_token_dropout,
      ft_use_cls = additional_params$ft_use_cls,
      saint_d_model = additional_params$saint_d_model,
      saint_heads = additional_params$saint_heads,
      saint_layers = additional_params$saint_layers,
      saint_ff_mult = additional_params$saint_ff_mult,
      saint_dropout = additional_params$saint_dropout,
      saint_token_dropout = additional_params$saint_token_dropout,
      saint_use_cls = additional_params$saint_use_cls,
      use_grouping = additional_params$use_grouping,
      group_trigger = additional_params$group_trigger,
      group_method = additional_params$group_method,
      init_group_size = additional_params$init_group_size,
      max_tokens = additional_params$max_tokens,
      kmeans_batch = additional_params$kmeans_batch,
      kmeans_iter = additional_params$kmeans_iter,
      tabnet_steps = additional_params$tabnet_steps,
      tabnet_feature_dim = additional_params$tabnet_feature_dim,
      tabnet_output_dim = additional_params$tabnet_output_dim,
      tabnet_gamma = additional_params$tabnet_gamma,
      tabnet_lambda_sparse = additional_params$tabnet_lambda_sparse,
      node_trees = additional_params$node_trees,
      node_depth = additional_params$node_depth,
      deepfm_k = additional_params$deepfm_k,
      deepfm_hidden = additional_params$deepfm_hidden,
      dcn_layers = additional_params$dcn_layers,
      dcn_hidden = additional_params$dcn_hidden,
      nam_hidden = additional_params$nam_hidden,
      nam_activation = additional_params$nam_activation,
      nam_add_linear = additional_params$nam_add_linear,
      nam_l1 = additional_params$nam_l1,
      moe_n_experts = additional_params$moe_n_experts,
      moe_expert_hidden = additional_params$moe_expert_hidden,
      moe_gate_hidden = additional_params$moe_gate_hidden,
      moe_temperature = additional_params$moe_temperature,
      moe_sparse_topk = additional_params$moe_sparse_topk,
      moe_entropy_reg = additional_params$moe_entropy_reg,
      gp_use_variational = additional_params$gp_use_variational,
      gp_num_inducing = additional_params$gp_num_inducing,
      gp_feature_dim = additional_params$gp_feature_dim,
      gp_kernel = additional_params$gp_kernel,
      gp_ard = additional_params$gp_ard,
      gp_lr_mult = additional_params$gp_lr_mult,
      rff_features = additional_params$rff_features,
      rff_lengthscale = additional_params$rff_lengthscale,
      rff_deep_hidden = additional_params$rff_deep_hidden,
      model_type = additional_params$model_type,
      epochs = additional_params$epochs,
      batch_size = additional_params$batch_size,
      dropout = additional_params$dropout,
      l2_weight_decay = additional_params$l2_weight_decay,
      l2_regularizer_dp = additional_params$l2_regularizer_dp,
      dropout_rate = additional_params$dropout_rate,
      batch_norm = additional_params$batch_norm,
      validation_split = additional_params$validation_split,
      compile_model = additional_params$compile_model,
      deterministic = additional_params$deterministic,
      random_seed = additional_params$random_seed,
      device = additional_params$device,
      mlp_neurons_per_layer = additional_params$mlp_neurons_per_layer,
      mlp_learning_rate = additional_params$mlp_learning_rate,
      final_attention = additional_params$final_attention,
      attention_across_multiple_layers = additional_params$attention_across_multiple_layers,
      heteroscedastic = additional_params$heteroscedastic
    ),
    "RandomForest" = AI_randomforest_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      response_family = additional_params$response_family,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      ntree = additional_params$ntree,
      mtry = additional_params$mtry,
      maxnodes = additional_params$maxnodes,
      nodesize = additional_params$nodesize,
      rf_n_jobs = additional_params$rf_n_jobs,
      omic_count = additional_params$omic_count
    ),
    "CatBoost" = AI_catboost_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      response_family = additional_params$response_family,
      catboost_iterations = additional_params$catboost_iterations,
      catboost_depth = additional_params$catboost_depth,
      catboost_learning_rate = additional_params$catboost_learning_rate,
      catboost_l2_leaf_reg = additional_params$catboost_l2_leaf_reg,
      catboost_thread_count = additional_params$catboost_thread_count,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      omic_count = additional_params$omic_count
    ),
    "LightGBM" = AI_lightgbm_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      response_family = additional_params$response_family,
      lightgbm_nrounds = additional_params$lightgbm_nrounds,
      lightgbm_learning_rate = additional_params$lightgbm_learning_rate,
      lightgbm_num_leaves = additional_params$lightgbm_num_leaves,
      lightgbm_feature_fraction = additional_params$lightgbm_feature_fraction,
      lightgbm_bagging_fraction = additional_params$lightgbm_bagging_fraction,
      lightgbm_min_data_in_leaf = additional_params$lightgbm_min_data_in_leaf,
      lightgbm_lambda_l1 = additional_params$lightgbm_lambda_l1,
      lightgbm_lambda_l2 = additional_params$lightgbm_lambda_l2,
      lightgbm_nthread = additional_params$lightgbm_nthread,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      omic_count = additional_params$omic_count
    ),
    "PartialLeastSquare" = AI_pls_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      ncomp = additional_params$ncomp,
      omic_count = additional_params$omic_count
    ),
    "Ridge_Regression" = AI_ridge_regression_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      omic_count = additional_params$omic_count
    ),
    "Lasso" = AI_lasso_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      omic_count = additional_params$omic_count
    ),
    "SupportVectorMachine" = AI_svm_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      response_family = additional_params$response_family,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      C_value = additional_params$C_value,
      degree_value = additional_params$degree_value,
      scale_value = additional_params$scale_value,
      offset_value = additional_params$offset_value,
      omic_count = additional_params$omic_count
    ),
    "K-NearestNeighbors" = AI_knn_cv(
      y = y,
      omics = omics_data,
      tst = tst,
      response_family = additional_params$response_family,
      scaling = additional_params$scaling,
      centering = additional_params$centering,
      k = additional_params$k,
      omic_count = additional_params$omic_count
    ),
    "KRR" = gp_backend_cv_predict(
      model_name = "KRR",
      y = y,
      tst = tst,
      additional_params = additional_params
    ),
    "GP" = gp_backend_cv_predict(
      model_name = "GP",
      y = y,
      tst = tst,
      additional_params = additional_params
    ),
    "GP_FA" = gp_backend_cv_predict(
      model_name = "GP_FA",
      y = y,
      tst = tst,
      additional_params = additional_params
    ),
    "LowRankGP" = gp_lowrank_cv_predict(
      y = y,
      tst = tst,
      additional_params = additional_params
    ),
    "GBLUP" = asreml_mod_cv(
      asreml_models_prep_cv = additional_params$asreml_models_prep_cv,
      pheno_data = additional_params$pheno_data,
      response = additional_params$response,
      heter_groups = additional_params$heter_groups,
      gen_name = additional_params$gen_name,
      tst = tst,
      weights = additional_params$weights,
      workspace = additional_params$workspace,
      pworkspace = additional_params$pworkspace,
      maxit = additional_params$maxit
    ),
    "Bayes" = bayes_mod_cv(
      y = y,
      ETA = additional_params$ETA,
      weights = additional_params$weights,
      bayes_para = additional_params$bayes_para,
      tst = tst,
      bayes_model = additional_params$bayes_model,
      bayes_trait = additional_params$bayes_trait,
      pheno_data = additional_params$pheno_data,
      response = additional_params$response,
      response_family = additional_params$response_family,
      groups = additional_params$bayes_groups,
      met_kernel_cv_meta = additional_params$met_kernel_cv_meta
    )
  )
}
